name: LightMeUp
main: com.kraken.lightmeup.Main
version: 1.3.1 (release)
commands: 
     lmu:
        description: Main LightMeUp settings command.
        usage: /<command> <on/off>
     light:
        description: Lights up the ground you walk on.
        usage: /<command>
     allowLight:
        description: Toggle player permission to use the light command.
        usage: /<command> <player>
        aliases: [allowLMU]